version: '2'
services:
  db:
    image: postgres:9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: myownpassword
      POSTGRES_USER: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      PGDB_TCP_PORT: 5432
      PGDB_TCP_HOST: db
      PGDB_USER: postgres
      PGDB_PASS: myownpassword
      PGDB_DB: parita
      PORT: 8000
    ports:
      - "8000:8000"
    links:
      - db
